s3:
  region: "us-east-1"
  buckets:
    bronze: "reddit-data-bronze-d271225"
    silver: "reddit-data-silver-d010126"

data_paths:
  raw_subreddits_popular:
    layer: bronze
    prefix: "subreddits/popular"
  raw_subreddits_new:
    layer: bronze
    prefix: "subreddits/new"
  raw_subreddits_hot:
    layer: bronze
    prefix: "subreddits/hot"
  raw_subreddits_rising:
    layer: bronze
    prefix: "subreddits/rising"

  cleaned_subreddits:
    layer: silver
    prefix: "subreddits"
