lemmy_api_base_url: "https://lemmy.world/api/v3"

s3:
  region: "us-east-1"
  buckets:
    bronze: "lemmy-bronze-data"
    silver: "lemmy-silver-data"
    gold: "lemmy-gold-data"

data_streams:
  posts:
    hot:
      sort: Hot
      limit: 50
    scaled:
      sort: Scaled
      limit: 50
    new:
      sort: New
      limit: 50
    active:
      sort: Active
      limit: 50
    top_day:
      sort: TopDay
      limit: 50
    top_week:
      sort: TopWeek
      limit: 50
    top_month:
      sort: TopMonth
      limit: 50
    top_year:
      sort: TopYear
      limit: 50
    top_all:
      sort: TopAll
      limit: 50
    most_comments:
      sort: MostComments
      limit: 50

  communities:
    hot:
      sort: Hot
      limit: 25
    new:
      sort: New
      limit: 25
    active:
      sort: Active
      limit: 25
    top_day:
      sort: TopDay
      limit: 25
    top_week:
      sort: TopWeek
      limit: 25
    top_month:
      sort: TopMonth
      limit: 25

gold:
  communities:
    tags: [hot, new, active, top_day, top_week, top_month]
  posts:
    tags: [hot, new, scaled, active, top_day, top_week, top_month, top_year, top_all, most_comments]

enrichment:
  active_community_threshold: 10  # users_active_week > threshold = active
